# Copyright 2013 Kevin Cox

################################################################################
#                                                                              #
#  This software is provided 'as-is', without any express or implied           #
#  warranty. In no event will the authors be held liable for any damages       #
#  arising from the use of this software.                                      #
#                                                                              #
#  Permission is granted to anyone to use this software for any purpose,       #
#  including commercial applications, and to alter it and redistribute it      #
#  freely, subject to the following restrictions:                              #
#                                                                              #
#  1. The origin of this software must not be misrepresented; you must not     #
#     claim that you wrote the original software. If you use this software in  #
#     a product, an acknowledgment in the product documentation would be       #
#     appreciated but is not required.                                         #
#                                                                              #
#  2. Altered source versions must be plainly marked as such, and must not be  #
#     misrepresented as being the original software.                           #
#                                                                              #
#  3. This notice may not be removed or altered from any source distribution.  #
#                                                                              #
################################################################################

# THIS FILE IS AUTOMATICALLY GENERATED ON INSTALL.  PLEASE DO NOT EDIT.
# Version information generated on Fri, 1 Nov 2013 18:09:01 -0400 (2013-11-01T18:09:01-04:00)

module R::Version

	def self.tag
		"v0.4.0"
	end

	def self.dist_from_tag
		15
	end

	def self.version_major
		"0"
	end

	def self.version_minor
		"4"
	end

	def self.version_patch
		"0"
	end

	def self.commit
		"7ad8a79cf9450a897503f6b03356d7bcaf7ac7a1"
	end

	def self.dirty?
		true
	end


	def self.rendered?
		true
	end
end
